//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBooking.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int RoomBookingID { get; set; }
        public Nullable<System.DateTime> BookedFrom { get; set; }
        public Nullable<System.DateTime> BookedUntil { get; set; }
        public string BookingStatus { get; set; }
        public string PaymentPaidStatus { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public int NoOfRoomsBook { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
